POST http://localhost:3000/assets
Content-Type: application/json

{
    "name": "Amazon",
    "symbol": "A1",
    "price": 100,
    "imagem": "AMZN.png"
}

###
GET http://localhost:3000/assets


###
GET http://localhost:3000/assets

###
POST http://localhost:3000/wallets

###
GET http://localhost:3000/wallets